name: Build and Push forked mhubai Docker Images

on:
  workflow_dispatch:

jobs:
  build-base:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push base image
        uses: docker/build-push-action@v5
        with:
          context: ./base
          file: ./base/dockerfiles/Dockerfile
          push: true
          tags: vamsithiriveedhi/mhubai_base
          
  build-models:
    runs-on: ubuntu-latest
    needs: build-base
    continue-on-error: true
    strategy:
      matrix:
        model: [casust, gc_lunglobes, lungmask, nnunet_liver, nnunet_pancreas, platipy, totalsegmentator]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push model image
        uses: docker/build-push-action@v5
        with:
          context: ./models/${{ matrix.model }}
          file: ./models/${{ matrix.model }}/dockerfiles/Dockerfile
          push: true
          tags: vamsithiriveedhi/mhubai_${{ matrix.model }}
